### ISSUE TITLE
Unable to render the base template when using Yarn v3.3.1 (berry)

### ISSUE THREAD

**Issue by favna** [nuxt-themes/docus#752] opened 2023-01-05 18:18 UTC
Running the dev server with Yarn v3.3.1 gives a 500 error when rendering the initial website.

Reproduction steps:
1. Run the following commands:
```sh
npx nuxi@latest init -t themes/docus
cd docs
rm pnpm-lock.yaml
rm .npmrc
yarn set version berry
yarn config set nodeLinker node-modules
yarn install
yarn dev
```
2. After the page loads the following error will be thrown in the console:
```
[nitro] [dev] [unhandledRejection] TypeError: Cannot read properties of undefined (reading 'fluid')                                                                     
    at _sfc_ssrRender (F:\dev\docs\node_modules\@nuxt-themes\docus\components\app\AppHeader.vue:54:32)
    at renderComponentSubTree (F:\dev\docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:254:17)
    at renderComponentVNode (F:\dev\docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:188:16)
    at Module.ssrRenderComponent (F:\dev\docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:624:12)
    at _sfc_ssrRender (F:\dev\docs\node_modules\@nuxt-themes\docus\components\app\AppLayout.vue:67:34)
    at renderComponentSubTree (F:\dev\docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:254:17)
    at renderComponentVNode (F:\dev\docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:188:16)
    at Module.ssrRenderComponent (F:\dev\docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:624:12)
    at _sfc_ssrRender (F:\dev\docs\node_modules\@nuxt-themes\docus\app.vue:15:31)
    at renderComponentSubTree (F:\dev\docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:254:17)
[nitro] [dev] [unhandledRejection] TypeError: Cannot read properties of undefined (reading 'fluid')                                                                     
    at _sfc_ssrRender (F:\dev\docs\node_modules\@nuxt-themes\docus\components\app\AppHeader.vue:54:32)
    at renderComponentSubTree (F:\dev\docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:254:17)
    at renderComponentVNode (F:\dev\docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:188:16)
    at Module.ssrRenderComponent (F:\dev\docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:624:12)
    at _sfc_ssrRender (F:\dev\docs\node_modules\@nuxt-themes\docus\components\app\AppLayout.vue:67:34)
    at renderComponentSubTree (F:\dev\docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:254:17)
    at renderComponentVNode (F:\dev\docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:188:16)
    at Module.ssrRenderComponent (F:\dev\docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:624:12)
    at _sfc_ssrRender (F:\dev\docs\node_modules\@nuxt-themes\docus\app.vue:15:31)
    at renderComponentSubTree (F:\dev\docs\node_modules\@vue\server-renderer\dist\server-renderer.cjs.js:254:17)
```
And in the browser:
```
500
Cannot read properties of undefined (reading 'fluid')

at Proxy._sfc_render (http://localhost:3000/_nuxt/node_modules/@nuxt-themes/docus/components/app/AppHeader.js:44:34)
at renderComponentRoot (http://localhost:3000/_nuxt/node_modules/.vite/deps/chunk-QO6ZHO7P.js?v=e72a52ed:1941:39)
at ReactiveEffect.componentUpdateFn [as fn] (http://localhost:3000/_nuxt/node_modules/.vite/deps/chunk-QO6ZHO7P.js?v=e72a52ed:5627:46)
at ReactiveEffect.run (http://localhost:3000/_nuxt/node_modules/.vite/deps/chunk-QO6ZHO7P.js?v=e72a52ed:388:19)
at instance.update (http://localhost:3000/_nuxt/node_modules/.vite/deps/chunk-QO6ZHO7P.js?v=e72a52ed:5723:52)
at setupRenderEffect (http://localhost:3000/_nuxt/node_modules/.vite/deps/chunk-QO6ZHO7P.js?v=e72a52ed:5731:5)
at mountComponent (http://localhost:3000/_nuxt/node_modules/.vite/deps/chunk-QO6ZHO7P.js?v=e72a52ed:5556:5)
at processComponent (http://localhost:3000/_nuxt/node_modules/.vite/deps/chunk-QO6ZHO7P.js?v=e72a52ed:5521:9)
at patch (http://localhost:3000/_nuxt/node_modules/.vite/deps/chunk-QO6ZHO7P.js?v=e72a52ed:5239:11)
at mountChildren (http://localhost:3000/_nuxt/node_modules/.vite/deps/chunk-QO6ZHO7P.js?v=e72a52ed:5384:7)
```

**Comment by Tahul** [comment] 2023-05-17 13:57
Hello!

Could you provide a reproduction as a repository or a sandboxed env please?

As this is old, I'll be closing this for now because I think that `Cannot read properties of undefined (reading 'fluid')` has been fixed!

Feel free to re-open if you encounter it again.

**Closed by Tahul** 2023-05-17 13:57 UTC
