### ISSUE TITLE
What about implementing a default offline search input?

### ISSUE THREAD

**Issue by otabekoff** [nuxt-themes/docus#771] opened 2023-01-20 18:35 UTC
Does an offline search input feature exist? Or should it be implemented? I've seen that many of SSGs or Static documentation generators have this function. One example is Vuepress. Let's say I'm making an app that works offline using PWA or real app with Docus. What the user does to search? Uses page by page manual checking? In my opinion it is the most hardest way to do it.

You can look up the Vuepress repo for the logic. Both Docus and Vuepress uses Vue(or Nuxt). 

EDIT: What about using DocSearch? I already know I can use Algolia. But it needs internet.

**Comment by marvin-j97** [comment] 2023-02-03 18:58
I'm guessing this is a duplicate of https://github.com/nuxt-themes/docus/issues/682 ?

[Nextra](https://github.com/shuding/nextra) uses [Flexsearch](https://github.com/nextapps-de/flexsearch).

For Docusaurus, there are [some plugins](https://docusaurus.io/community/resources#search) that use [Lunr](https://lunrjs.com/).

**Comment by Tahul** [comment] 2023-05-17 13:58
This is related to #682

**Closed** 2023-05-17 14:00 UTC
